#--------------------------------------------------------------
#          Makefile for sw module
#--------------------------------------------------------------

# List module object filenames
spinwave_objects =\
data.o \
initialize.o \
interface.o \
spinwaves.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/spinwaves/,$(spinwave_objects))
