#--------------------------------------------------------------
#          Makefile for spinwaves module
#--------------------------------------------------------------

# List module object filenames
spinwaves_objects =\
data.o \
initialize.o \
interface.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/spinwaves/,$(spinwaves_objects))
